#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SERVICES_SOURCE="${ROOT_DIR}/config/services.yaml"
HOSTS_SOURCE="${ROOT_DIR}/config/hosts.yaml"
OUTPUT_DIR="${ROOT_DIR}/services/traefik/dynamic"
OUTPUT="${OUTPUT_DIR}/routes.yml"

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but was not found."
    echo "Install yq: https://github.com/kislyuk/yq"
    exit 1
fi

if [[ ! -f "${SERVICES_SOURCE}" ]]; then
    echo "Error: services configuration not found:"
    echo "  ${SERVICES_SOURCE}"
    exit 1
fi

if [[ ! -f "${HOSTS_SOURCE}" ]]; then
    echo "Error: hosts configuration not found:"
    echo "  ${HOSTS_SOURCE}"
    exit 1
fi

source "${ROOT_DIR}/scripts/generation/lib.sh"

mkdir -p "${OUTPUT_DIR}"

echo "Generating Traefik dynamic configuration..."

# Map each service name to a backend LAN address: a host whose key matches
# the service name directly (homepage, it-tools, ...), falling back to a
# host whose `role` list includes the service name (grafana/prometheus/
# loki/alertmanager all run on the shared "monitoring" host, not on a host
# of their own). Exact key matches win over role matches.
# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
ADDR_MAP="$(yq -c --argjson resolved "$(resolve_addresses "${HOSTS_SOURCE}")" '
  .hosts as $hosts
  | ($hosts | to_entries | map({key: (.value.role // [])[], value: $resolved[.key]}) | from_entries) as $by_role
  | $resolved as $by_key
  | $by_role * $by_key
' "${HOSTS_SOURCE}")"

# Traefik only fronts `personal`/`public` tier traffic (Cloudflared ->
# Traefik -> backend); `internal` services are plain LAN IP:port and never
# get a router here. Each service can contribute up to two exposures: its
# own top-level tier (if personal/public) and an `external:` alias (a
# service that's internal day-to-day but also has a public/personal alias,
# e.g. Jellyfin) — both resolve to the same backend host. See
# config/README.md#tier and #external.
# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
EXPOSURES="$(yq -c '
  [
    .services
    | to_entries[]
    | .key as $key
    | .value as $svc
    | (
        (if (($svc.tier == "personal") or ($svc.tier == "public")) and ($svc.traefik.enabled == true) then
          [{router: $key, base: $key, url: $svc.url, port: $svc.traefik.port}]
        else [] end)
        +
        (if ($svc.external != null)
            and (($svc.external.tier == "personal") or ($svc.external.tier == "public"))
            and ($svc.external.traefik.enabled == true) then
          [{router: ($key + "-remote"), base: $key, url: $svc.external.url, port: $svc.external.traefik.port}]
        else [] end)
      )[]
  ]
' "${SERVICES_SOURCE}")"

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
ROUTERS="$(yq -r --argjson addrs "${ADDR_MAP}" '
  .[]
  | (if $addrs[.base] == null then
      "no backend host found for service \"\(.base)\" in config/hosts.yaml" | halt_error
    else . end)
  | (.url | sub("^https?://"; "")) as $host
  | "    \(.router):\n      rule: \"Host(`\($host)`)\"\n      entryPoints: [\"web\"]\n      service: \(.router)"
' <<<"${EXPOSURES}")"

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
BACKENDS="$(yq -r --argjson addrs "${ADDR_MAP}" '
  .[]
  | $addrs[.base] as $addr
  | "    \(.router):\n      loadBalancer:\n        servers:\n          - url: \"http://\($addr):\(.port)\""
' <<<"${EXPOSURES}")"

{
    cat <<'EOF'
# This file is generated.
# Do not edit manually.
# Source: config/services.yaml, config/hosts.yaml
# Generated by: scripts/generation/generate-traefik.sh
#
# Traefik only fronts `personal`/`public` tier traffic arriving from
# Cloudflared (see services/cloudflared/config.yml, also generated) —
# `internal` services are plain LAN IP:port and never routed through here.
# A service opts in with a `traefik: {enabled: true, port: <n>}` block
# (top-level, or nested under `external:` for a service that's internal
# but also has a remote-access alias). Plain HTTP: Cloudflare Tunnel
# already encrypts the public leg up to the cloudflared LXC, so this
# internal hop doesn't need its own TLS.
http:
  routers:
EOF
    echo "${ROUTERS}"
    echo "  services:"
    echo "${BACKENDS}"
} >"${OUTPUT}"

echo ""
echo "Traefik dynamic configuration generated:"
echo "  ${OUTPUT}"
