#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SOURCE="${ROOT_DIR}/config/hosts.yaml"
OUTPUT_DIR="${ROOT_DIR}/ansible/inventory"
OUTPUT="${OUTPUT_DIR}/hosts.yml"

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but was not found."
    echo "Install yq: https://github.com/kislyuk/yq"
    exit 1
fi

if [[ ! -f "${SOURCE}" ]]; then
    echo "Error: hosts configuration not found:"
    echo "  ${SOURCE}"
    exit 1
fi

source "${ROOT_DIR}/scripts/generation/lib.sh"

mkdir -p "${OUTPUT_DIR}"

echo "Generating Ansible inventory..."

RESOLVED="$(resolve_addresses "${SOURCE}")"

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
SKIPPED="$(yq -r --argjson resolved "${RESOLVED}" '
  .hosts | to_entries[]
  | select($resolved[.key] == "TBD")
  | .key
' "${SOURCE}")"
if [[ -n "${SKIPPED}" ]]; then
    echo "Warning: skipping hosts without a confirmed address (address: TBD):"
    while IFS= read -r host; do
        echo "  - ${host}"
    done <<<"${SKIPPED}"
fi

{
    echo "# This file is generated."
    echo "# Do not edit manually."
    echo "# Source: config/hosts.yaml"
    echo "# Generated by: scripts/generation/generate-inventory.sh"
    echo ""
    # all.vars carries network-wide facts (config/hosts.yaml's network:
    # block) that roles need but can't get from a per-host ansible_host —
    # e.g. wireguard's ALLOWEDIPS derives from lan_cidr instead of
    # hardcoding the LAN subnet.
    #
    # ansible_user mirrors what terraform/proxmox actually provisions:
    # LXCs get their SSH key on root (lxc.tf's user_account has no
    # username, so bpg/proxmox defaults it to root), VMs get it on
    # var.vm_user's default "ansible" (vms.tf sets username explicitly).
    # If you change vm_user in terraform.tfvars, update the "ansible"
    # literal below to match.
    # shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
    yq -y --argjson resolved "${RESOLVED}" '
      .hosts as $hosts
      | .network as $net
      | ($hosts | to_entries | map(select($resolved[.key] != "TBD"))) as $valid
      | (
          ([$valid[] | .key]) + ([$valid[] | (.value.role // [])[]])
        ) as $group_names
      | {
          all: {
            vars: {
              lan_cidr: ($net.lan.prefix + ".0/" + ($net.lan.mask | tostring)),
              lan_gateway: $net.lan.gateway
            },
            children: (
              ($group_names | unique) as $groups
              | reduce $groups[] as $g (
                  {};
                  . + {
                    ($g): {
                      hosts: (
                        reduce $valid[] as $h (
                          {};
                          if ($h.key == $g) or (($h.value.role // []) | index($g))
                          then . + { ($h.key): {
                              ansible_host: $resolved[$h.key],
                              ansible_user: (if $h.value.type == "vm" then "ansible" else "root" end)
                            } }
                          else .
                          end
                        )
                      )
                    }
                  }
                )
            )
          }
        }
    ' "${SOURCE}"
} > "${OUTPUT}"

echo ""
echo "Ansible inventory generated:"
echo "  ${OUTPUT}"
