#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SERVICES_SOURCE="${ROOT_DIR}/config/services.yaml"
HOSTS_SOURCE="${ROOT_DIR}/config/hosts.yaml"
OUTPUT_DIR="${ROOT_DIR}/services/traefik/dynamic"
OUTPUT="${OUTPUT_DIR}/routes.yml"

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but was not found."
    echo "Install yq: https://github.com/kislyuk/yq"
    exit 1
fi

if [[ ! -f "${SERVICES_SOURCE}" ]]; then
    echo "Error: services configuration not found:"
    echo "  ${SERVICES_SOURCE}"
    exit 1
fi

if [[ ! -f "${HOSTS_SOURCE}" ]]; then
    echo "Error: hosts configuration not found:"
    echo "  ${HOSTS_SOURCE}"
    exit 1
fi

source "${ROOT_DIR}/scripts/generation/lib.sh"

mkdir -p "${OUTPUT_DIR}"

echo "Generating Traefik dynamic configuration..."

# Map each service name to a backend LAN address: a host whose key matches
# the service name directly (homepage, it-tools, ...), falling back to a
# host whose `role` list includes the service name (grafana/prometheus/
# loki/alertmanager all run on the shared "monitoring" host, not on a host
# of their own). Exact key matches win over role matches.
# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
ADDR_MAP="$(yq -c --argjson resolved "$(resolve_addresses "${HOSTS_SOURCE}")" '
  .hosts as $hosts
  | ($hosts | to_entries | map({key: (.value.role // [])[], value: $resolved[.key]}) | from_entries) as $by_role
  | $resolved as $by_key
  | $by_role * $by_key
' "${HOSTS_SOURCE}")"

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
ROUTERS="$(yq -r --argjson addrs "${ADDR_MAP}" '
  .services
  | to_entries[]
  | select(.value.traefik.enabled == true)
  | .key as $name
  | (if $addrs[$name] == null then
      "no backend host found for service \"\($name)\" in config/hosts.yaml" | halt_error
    else . end)
  | (.value.url | sub("^https?://"; "")) as $host
  | "    \($name):\n      rule: \"Host(`\($host)`)\"\n      entryPoints: [\"websecure\"]\n      service: \($name)\n      tls: {}"
' "${SERVICES_SOURCE}")"

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
BACKENDS="$(yq -r --argjson addrs "${ADDR_MAP}" '
  .services
  | to_entries[]
  | select(.value.traefik.enabled == true)
  | .key as $name
  | $addrs[$name] as $addr
  | .value.traefik.port as $port
  | "    \($name):\n      loadBalancer:\n        servers:\n          - url: \"http://\($addr):\($port)\""
' "${SERVICES_SOURCE}")"

{
    cat <<'EOF'
# This file is generated.
# Do not edit manually.
# Source: config/services.yaml, config/hosts.yaml
# Generated by: scripts/generation/generate-traefik.sh
#
# config/services.yaml declares the https://<name>.home.arpa URLs; this
# file is what actually makes them resolve to something once AdGuard Home
# points *.home.arpa at Traefik (see README.md). A service opts in with a
# `traefik: {enabled: true, port: <n>}` block.
http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.home.arpa`)"
      entryPoints: ["websecure"]
      service: api@internal
      tls: {}
EOF
    echo "${ROUTERS}"
    echo "  services:"
    echo "${BACKENDS}"
} >"${OUTPUT}"

echo ""
echo "Traefik dynamic configuration generated:"
echo "  ${OUTPUT}"
