#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SOURCE="${ROOT_DIR}/config/hosts.yaml"
OUTPUT_DIR="${ROOT_DIR}/ansible/inventory"
OUTPUT="${OUTPUT_DIR}/hosts.yml"

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but was not found."
    echo "Install yq: https://github.com/kislyuk/yq"
    exit 1
fi

if [[ ! -f "${SOURCE}" ]]; then
    echo "Error: hosts configuration not found:"
    echo "  ${SOURCE}"
    exit 1
fi

mkdir -p "${OUTPUT_DIR}"

echo "Generating Ansible inventory..."

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
SKIPPED="$(yq -r '.hosts | to_entries[] | select(.value.address == "TBD") | .key' "${SOURCE}")"
if [[ -n "${SKIPPED}" ]]; then
    echo "Warning: skipping hosts without a confirmed address (address: TBD):"
    while IFS= read -r host; do
        echo "  - ${host}"
    done <<<"${SKIPPED}"
fi

{
    echo "# This file is generated."
    echo "# Do not edit manually."
    echo "# Source: config/hosts.yaml"
    echo "# Generated by: scripts/generation/generate-inventory.sh"
    echo ""
    # shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
    yq -y '
      .hosts as $hosts
      | ($hosts | to_entries | map(select(.value.address != "TBD"))) as $valid
      | (
          ([$valid[] | .key]) + ([$valid[] | (.value.role // [])[]])
        ) as $group_names
      | {
          all: {
            children: (
              ($group_names | unique) as $groups
              | reduce $groups[] as $g (
                  {};
                  . + {
                    ($g): {
                      hosts: (
                        reduce $valid[] as $h (
                          {};
                          if ($h.key == $g) or (($h.value.role // []) | index($g))
                          then . + { ($h.key): { ansible_host: $h.value.address } }
                          else .
                          end
                        )
                      )
                    }
                  }
                )
            )
          }
        }
    ' "${SOURCE}"
} > "${OUTPUT}"

echo ""
echo "Ansible inventory generated:"
echo "  ${OUTPUT}"
