#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SERVICES_SOURCE="${ROOT_DIR}/config/services.yaml"
HOSTS_SOURCE="${ROOT_DIR}/config/hosts.yaml"
OUTPUT="${ROOT_DIR}/services/cloudflared/config.yml"

# The internal HTTP entrypoint Traefik listens on for traffic forwarded by
# Cloudflared (services/traefik/traefik.yml's "web" entryPoint). Not
# config/-owned data — it's an implementation detail of the traefik role,
# same category as its image tag. Keep this in sync with traefik.yml.
TRAEFIK_PORT=80

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but was not found."
    echo "Install yq: https://github.com/kislyuk/yq"
    exit 1
fi

if [[ ! -f "${SERVICES_SOURCE}" ]]; then
    echo "Error: services configuration not found:"
    echo "  ${SERVICES_SOURCE}"
    exit 1
fi

if [[ ! -f "${HOSTS_SOURCE}" ]]; then
    echo "Error: hosts configuration not found:"
    echo "  ${HOSTS_SOURCE}"
    exit 1
fi

source "${ROOT_DIR}/scripts/generation/lib.sh"

echo "Generating Cloudflare Tunnel ingress configuration..."

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
TRAEFIK_ADDR="$(yq -r --argjson resolved "$(resolve_addresses "${HOSTS_SOURCE}")" -n '$resolved.traefik')"

if [[ -z "${TRAEFIK_ADDR}" || "${TRAEFIK_ADDR}" == "null" || "${TRAEFIK_ADDR}" == "TBD" ]]; then
    echo "Error: could not resolve a LAN address for the \"traefik\" host in config/hosts.yaml."
    exit 1
fi

TARGET="http://${TRAEFIK_ADDR}:${TRAEFIK_PORT}"

# The real tunnel ID is a one-time value from `cloudflared tunnel create`
# (see services/cloudflared/README.md), not something config/ knows about.
# Preserve it across regenerations instead of clobbering it back to the
# placeholder every time someone runs `make generate` for an unrelated
# reason.
TUNNEL_ID="REPLACE_WITH_TUNNEL_ID"
if [[ -f "${OUTPUT}" ]]; then
    EXISTING_TUNNEL_ID="$(grep -m1 '^tunnel:' "${OUTPUT}" | sed 's/^tunnel: *//')"
    if [[ -n "${EXISTING_TUNNEL_ID}" ]]; then
        TUNNEL_ID="${EXISTING_TUNNEL_ID}"
    fi
fi

# Every `personal`/`public` exposure (top-level tier, or `external:` for a
# service that's internal but also has a remote-access alias) becomes an
# ingress hostname pointing at Traefik — never at the backend directly.
# Traefik does the actual per-service routing (see generate-traefik.sh).
# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
PUBLIC_HOSTS="$(yq -r '
  .services
  | to_entries[]
  | .value as $svc
  | (
      (if (($svc.tier == "public") and ($svc.traefik.enabled == true)) then [$svc.url] else [] end)
      +
      (if ($svc.external != null) and ($svc.external.tier == "public") and ($svc.external.traefik.enabled == true) then [$svc.external.url] else [] end)
    )[]
  | sub("^https?://"; "")
' "${SERVICES_SOURCE}" | sort)"

# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
PERSONAL_HOSTS="$(yq -r '
  .services
  | to_entries[]
  | .value as $svc
  | (
      (if (($svc.tier == "personal") and ($svc.traefik.enabled == true)) then [$svc.url] else [] end)
      +
      (if ($svc.external != null) and ($svc.external.tier == "personal") and ($svc.external.traefik.enabled == true) then [$svc.external.url] else [] end)
    )[]
  | sub("^https?://"; "")
' "${SERVICES_SOURCE}" | sort)"

{
    cat <<EOF
# This file is generated.
# Do not edit manually.
# Source: config/services.yaml, config/hosts.yaml
# Generated by: scripts/generation/generate-cloudflared.sh
#
# Every hostname below forwards to Traefik, never straight to a backend —
# Traefik does the per-service routing from the same catalog, see
# services/traefik/dynamic/routes.yml. Target: ${TARGET}
# \`tunnel:\` is a one-time value from \`cloudflared tunnel create\` (see
# services/cloudflared/README.md), preserved across regenerations once
# set — it is not config/-owned data, this generator only avoids
# clobbering it back to the placeholder.
tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
EOF

    if [[ -n "${PUBLIC_HOSTS}" ]]; then
        echo "  # sisqueslabs.com — public homelab apps"
        while IFS= read -r host; do
            echo "  - hostname: ${host}"
            echo "    service: ${TARGET}"
        done <<<"${PUBLIC_HOSTS}"
    fi

    if [[ -n "${PERSONAL_HOSTS}" ]]; then
        echo "  # jsisques.net — personal apps"
        while IFS= read -r host; do
            echo "  - hostname: ${host}"
            echo "    service: ${TARGET}"
        done <<<"${PERSONAL_HOSTS}"
    fi

    echo ""
    echo "  # Anything not matched above is refused rather than silently routed."
    echo "  - service: http_status:404"
} >"${OUTPUT}"

echo ""
echo "Cloudflare Tunnel ingress configuration generated:"
echo "  ${OUTPUT}"
