#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SERVICES_SOURCE="${ROOT_DIR}/config/services.yaml"
HOSTS_SOURCE="${ROOT_DIR}/config/hosts.yaml"
OUTPUT_DIR="${ROOT_DIR}/services/prometheus"
OUTPUT="${OUTPUT_DIR}/blackbox-targets.yml"

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but was not found."
    echo "Install yq: https://github.com/kislyuk/yq"
    exit 1
fi

if [[ ! -f "${SERVICES_SOURCE}" ]]; then
    echo "Error: services configuration not found:"
    echo "  ${SERVICES_SOURCE}"
    exit 1
fi

if [[ ! -f "${HOSTS_SOURCE}" ]]; then
    echo "Error: hosts configuration not found:"
    echo "  ${HOSTS_SOURCE}"
    exit 1
fi

source "${ROOT_DIR}/scripts/generation/lib.sh"

mkdir -p "${OUTPUT_DIR}"

echo "Generating blackbox_exporter targets..."

# Same host-resolution technique as generate-traefik.sh: match host key
# first, falling back to a host whose `role` list contains the service
# name. pbs and k3s-server are themselves host keys in config/hosts.yaml
# (they have minimal config/services.yaml entries that exist only to
# carry a `blackbox:` block — no host of their own beyond that), so they
# resolve directly with no role fallback needed.
# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
ADDR_MAP="$(yq -c --argjson resolved "$(resolve_addresses "${HOSTS_SOURCE}")" '
  .hosts as $hosts
  | ($hosts | to_entries | map({key: (.value.role // [])[], value: $resolved[.key]}) | from_entries) as $by_role
  | $resolved as $by_key
  | $by_role * $by_key
' "${HOSTS_SOURCE}")"

# Services opt in with a `blackbox: {enabled: true, port: <n>, scheme:
# http|https, module: <name>}` block. Targets are grouped by module,
# since blackbox_exporter's file_sd_config groups targets that share a
# probe module under one `labels:` block (group_by sorts+groups
# alphabetically by module, which also happens to match the original
# hand-authored file's http_2xx / http_2xx_insecure split).
# shellcheck disable=SC2016 # single quotes are intentional: this is a jq filter, not a shell expansion
TARGET_GROUPS="$(yq -r --argjson addrs "${ADDR_MAP}" '
  [ .services
    | to_entries[]
    | select(.value.blackbox.enabled == true)
    | .key as $name
    | (if $addrs[$name] == null then
        "no backend host found for service \"\($name)\" in config/hosts.yaml" | halt_error
      else . end)
    | {
        name: $name,
        module: .value.blackbox.module,
        target: "\(.value.blackbox.scheme // "http")://\($addrs[$name]):\(.value.blackbox.port)"
      }
  ]
  | group_by(.module)
  | map(
      "- targets:\n"
      + (map("    - \"\(.target)\"  # \(.name)") | join("\n"))
      + "\n  labels:\n    module: \(.[0].module)"
    )
  | join("\n")
' "${SERVICES_SOURCE}")"

{
    cat <<'EOF'
# This file is generated.
# Do not edit manually.
# Source: config/services.yaml, config/hosts.yaml
# Generated by: scripts/generation/generate-blackbox.sh
#
# Prometheus file_sd_config: targets for services with no native /metrics
# endpoint, probed by blackbox_exporter instead for basic up/down +
# latency. A service opts in with a `blackbox: {enabled: true, port: <n>,
# scheme: http|https, module: <name>}` block in config/services.yaml —
# see services/blackbox-exporter/README.md for available modules.
EOF
    echo "${TARGET_GROUPS}"
} >"${OUTPUT}"

echo ""
echo "blackbox_exporter targets generated:"
echo "  ${OUTPUT}"
