apiVersion: apps/v1
kind: Deployment
metadata:
  name: sisqueslabs-landing
  namespace: sisqueslabs-landing
  labels:
    app.kubernetes.io/name: sisqueslabs-landing
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: sisqueslabs-landing

  template:
    metadata:
      labels:
        app.kubernetes.io/name: sisqueslabs-landing
    spec:
      containers:
        - name: sisqueslabs-landing
          image: sisqueslabs/sisques-labs-landing:latest
          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /healthz
              port: http

          livenessProbe:
            httpGet:
              path: /healthz
              port: http

          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
