---
- name: Create WireGuard application directory
  ansible.builtin.file:
    path: "{{ wireguard_app_dir }}"
    state: directory
    mode: "0755"

- name: Deploy WireGuard environment file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ wireguard_app_dir }}/.env"
    mode: "0644"

- name: Deploy WireGuard Docker Compose file
  ansible.builtin.copy:
    src: "{{ services_dir }}/wireguard/compose.yaml"
    dest: "{{ wireguard_app_dir }}/compose.yaml"
    mode: "0644"

- name: Start WireGuard
  community.docker.docker_compose_v2:
    project_src: "{{ wireguard_app_dir }}"
    state: present
