services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped

    command: ["--config=/etc/otelcol-contrib/config.yaml"]

    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus exporter (scraped by Prometheus)

    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml:ro

networks:
  default:
    name: monitoring
    external: true
