services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"

    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
