entryPoints:
  web:
    address: ":80"
  metrics:
    address: ":8082"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true

log:
  level: INFO
