services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - portainer-data:/data

volumes:
  portainer-data:

networks:
  default:
    name: monitoring
    external: true
