hosts:
  proxmox:
    type: server
    platform: proxmox
    address: TBD # LAN IP not confirmed yet
    role:
      - hypervisor

  nas:
    type: physical
    platform: nas
    address: 192.168.0.111
    role:
      - storage

  monitoring:
    type: lxc
    platform: proxmox
    address: 192.168.1.20
    role:
      - prometheus
      - grafana

  homepage:
    type: lxc
    platform: proxmox
    address: 192.168.1.21
    role:
      - homepage

  uptime-kuma:
    type: lxc
    platform: proxmox
    address: 192.168.1.22
    role:
      - uptime-kuma

  it-tools:
    type: lxc
    platform: proxmox
    address: 192.168.1.23
    role:
      - it-tools

  n8n:
    type: lxc
    platform: proxmox
    address: 192.168.1.24
    role:
      - n8n

  cloudflared:
    type: lxc
    platform: proxmox
    address: 192.168.1.25
    role:
      - cloudflared

  raspberrypi-01:
    type: physical
    platform: raspberry-pi
    address: 192.168.1.40
    role:
      - k3s
      - worker

  raspberrypi-02:
    type: physical
    platform: raspberry-pi
    address: 192.168.1.41
    role:
      - k3s
      - worker
