---
- ansible.builtin.import_playbook: it-tools.yaml
- ansible.builtin.import_playbook: n8n.yaml
- ansible.builtin.import_playbook: monitoring.yaml
- ansible.builtin.import_playbook: homepage.yaml
- ansible.builtin.import_playbook: uptime-kuma.yaml
- ansible.builtin.import_playbook: cloudflared.yaml
