---
- name: Create Portfolio Web application directory
  ansible.builtin.file:
    path: "{{ portfolio_web_app_dir }}"
    state: directory
    mode: "0755"

- name: Deploy Portfolio Web Docker Compose file
  ansible.builtin.copy:
    src: "{{ services_dir }}/portfolio-web/compose.yaml"
    dest: "{{ portfolio_web_app_dir }}/compose.yaml"
    mode: "0644"

- name: Pull and start Portfolio Web
  community.docker.docker_compose_v2:
    project_src: "{{ portfolio_web_app_dir }}"
    pull: always
    state: present
