services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/config.yml

    volumes:
      - ./config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki

volumes:
  loki-data:

networks:
  default:
    name: monitoring
    external: true
